name: Digital Democracy
description: Empowering marginalized communities to use technology to defend their rights
url: https://www.digital-democracy.org/
timezone: America/Los_Angeles
markdown: kramdown
incremental: false
permalink: /:categories/:title/
gems: ['jekyll-paginate']
exclude:
  - wp-content
  - sass
  - config.rb
  - README.md
  - .gitignore
  - .tm_properties
  - CNAME
  - config.ru
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor
  - Procfile
  - Rakefile
  - node_modules
include:
  - _redirects
collections:
  team_and_board:
    output: true
    permalink: /team/:title/
  projects:
    output: true
    permalink: /ourwork/:path/
  aboutus:
    output: true
    permalink: /:path/
  mapeo:
    output: true
    permalink: /mapeo/:path/
  jobs:
    output: true
    permalink: /jobs/:path/
  internships:
    output: true
    permalink: /jobs/:path/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
      class: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "article"
      class: "project"
  -
    scope:
      path: ""
      type: "team_and_board"
    values:
      layout: "team"
      class: "team"
paginate: 10
paginate_path: /blog/:num/
sass:
  style: :nested
  line_comments: true
prose:
  siteurl: "https://www.digital-democracy.org"
  media: "assets"
  ignore:
    - /_psd
    - /_archived
    - _drafts
    - /_includes
    - /_layouts
    - /_sass
    - /assets
    - /js
    - /css
    - /wp-content
    - /_index_pages
    - /donate
    - /ourwork
    - /team
    - /.gitignore
    - /.jsbeautifyrc
    - /CNAME
    - /_config.yml
    - /favicon.ico
    - /feed.xml
    - /humans.txt
    - /Makefile
    - /robots.txt
    - /tags.jsonp
    - /blog
    - /config.ru
    - /Gemfile
    - /Gemfile.lock
    - /vendor
    - /Procfile
    - /Rakefile
  metadata:
    _posts:
    _posts/archive:
      - name: "title"
        field:
          element: "text"
          label: "Post Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          placeholder: "Enter your name"
      - name: "image"
        field:
          element: "text"
          label: "Featured image"
          value: ""
          placeholder: "Enter a URL"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: "https://www.digital-democracy.org/tags.jsonp?callback=tags"
          alterable: true
      - name: "categories"
        field:
          element: "button"
          label: "Archived (permalink remains, but not listed on blog)"
          on: "post"
          off: "archive"
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Post Title"
          value: "Post Title"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          placeholder: "Enter your name"
          help: "This should be the full name, matching the full name used in the team page metadata (if writer is on that page)"
      - name: "excerpt"
        field:
          element: "text"
          label: "Post Excerpt"
          help: "This excerpt is used for the blog posts on the front page and in list view. If this is blank the first paragraph of the post will be used"
      - name: "image"
        field:
          element: "text"
          label: "Post image"
          help: "URL should start with /assets - upload with Github"
          placeholder: "Enter a URL"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: "https://www.digital-democracy.org/tags.jsonp?callback=tags"
          alterable: true
          help: "The most recent post tagged 'Featured' will appear at the top of the blog page. The 5 most recent posts tagged 'Front page' will appear as large images at the top of the front page."
      - name: "categories"
        field:
          element: "hidden"
          value: "blog"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
    _projects:
      - name: "title"
        field:
          element: "text"
          label: "Project Title"
          value: "Project Title"
      - name: "image"
        field:
          element: "text"
          label: "Featured image"
          help: "URL should start with /assets"
          value: ""
          placeholder: "Enter a URL"
      - name: "featured"
        field:
          element: "select"
          label: "Feature Project?"
          options:
            - name: "Featured Large"
              value: "large"
            - name: "Featured Medium"
              value: "medium"
            - name: "Featured Small"
              value: "small"
            - name: "No"
              value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Select tag(s) to list related blog posts"
          options: "https://www.digital-democracy.org/tags.jsonp?callback=tags"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
    _team_and_board:
      - name: "title"
        field:
          element: "text"
          label: "Name"
          value: "Full Name"
      - name: "role"
        field:
          element: "text"
          label: "Role"
          value: ""
          placeholder: "Job Title"
      - name: "current"
        field:
          element: "checkbox"
          help: "Set to false to hide staff/board member"
          value: true
          label: "Current staff/board?"
      - name: "email"
        field:
          element: "text"
          label: "Email Address"
          placeholder: "Enter email"
      - name: "twitter"
        field:
          element: "text"
          required: false
          label: "Twitter Profile"
          placeholder: "Enter URL to Twitter feed"
      - name: "image"
        field:
          element: "text"
          label: "Profile image"
          help: "Start with / e.g. /assets/my-image.jpg - upload the image in Github as a JPEG file"
          value: ""
          placeholder: "Enter a URL"
      - name: "tags"
        field:
          element: "select"
          label: "Core Team (Staff) / Board / Advisor"
          placeholder: "Select an option"
          options:
            - name: "Core Team"
              value: "core"
            - name: "Board"
              value: "board"
            - name: "Advisor"
              value: "advisor"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          placeholder: "Enter URL e.g. /team/emily"
          help: "This will be the URL for this persons team page. Should start with /team/ generally followed by their first name"
      - name: "layout"
        field:
          element: "hidden"
          value: "team"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
    _jobs:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: "Job Title"
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
          help: "Two-line excerpt job description"
      - name: "layout"
        field:
          element: "hidden"
          value: "job"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
    _internships:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: "Job Title"
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
          help: "Two-line excerpt intership description"
      - name: "layout"
        field:
          element: "hidden"
          value: "job"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
