name: Digital Democracy
description: Educating 21st Century Citizens
url: http://www.digital-democracy.org
timezone: America/NewYork
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'no_intra_emphasis', 'autolink']
permalink: /:categories/:title/
exclude: 
  - wp-content
  - sass
  - config.rb
  - README.md
  - .gitignore
  - .tm_properties
  - CNAME
collections:
  team_and_board:
    output: true
    permalink: /team/:title/
  projects:
    output: true
    permalink: /ourwork/:path/
paginate: 10
paginate_path: "blog/:num/"
sass:
  style: :nested
  line_comments: true
