name: Digital Democracy
description: Educating 21st Century Citizens
timezone: America/NewYork
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'no_intra_emphasis', 'autolink']
permalink: pretty
exclude: 
  - wp-content
  - sass
  - config.rb
  - README.md
  - .gitignore
  - .tm_properties
  - CNAME