name: Digital Democracy
description: Educating 21st Century Citizens
timezone: America/NewYork
markdown: rdiscount
permalink: pretty
exclude: 
  - wp-content
  - sass
  - config.rb
  - README.md
  - .gitignore
  - .tm_properties
  - CNAME