name: Digital Democracy
description: Educating 21st Century Citizens
url: http://www.digital-democracy.org
timezone: America/NewYork
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'no_intra_emphasis', 'autolink']
permalink: /:categories/:title/
exclude: 
  - wp-content
  - sass
  - config.rb
  - README.md
  - .gitignore
  - .tm_properties
  - CNAME
  - psd
collections:
  team_and_board:
    output: true
    permalink: /team/:title/
  projects:
    output: true
    permalink: /ourwork/:path/
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
      class: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "article"
      class: "project"
  -
    scope:
      path: ""
      type: "team_and_board"
    values:
      layout: "team"
      class: "team"
paginate: 10
paginate_path: "blog/:num/"
sass:
  style: :nested
  line_comments: true
prose:
  siteurl: "http://www.digital-democracy.org"
  media: "assets"
  ignore:
    - _psd
  metadata:
    _posts:
    _posts/archive:
      - name: "title"
        field:
          element: "text"
          label: "Post Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          placeholder: "Enter your name"
      - name: "image"
        field:
          element: "text"
          label: "Featured image"
          value: ""
          placeholder: "Enter a URL"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: "http://www.digital-democracy.org/tags.jsonp?callback=tags"
          alterable: true
      - name: "categories"
        field:
          element: "button"
          label: "Archived (permalink remains, but not listed on blog)"
          on: "post"
          off: "archive"
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Post Title"
          value: "Post Title"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          placeholder: "Enter your name"
      - name: "excerpt"
        field:
          element: "text"
          label: "Post Excerpt"
      - name: "image"
        field:
          element: "text"
          label: "Post image"
          placeholder: "Enter a URL"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: "http://www.digital-democracy.org/tags.jsonp?callback=tags"
          alterable: true
      - name: "categories"
        field:
          element: "hidden"
          value: "blog"
    _posts/projects:
      - name: "title"
        field:
          element: "text"
          label: "Project Title"
          value: "Project Title"
      - name: "image"
        field:
          element: "text"
          label: "Featured image"
          value: ""
          placeholder: "Enter a URL"
      - name: "featured"
        field:
          element: "select"
          label: "Feature Project?"
          options:
            - name: "Featured Large"
              value: "large"
            - name: "Featured Medium"
              value: "medium"
            - name: "Featured Small"
              value: "small"
            - name: "No"
              value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Select tag(s) to list related blog posts"
          options: "http://www.digital-democracy.org/tags.jsonp?callback=tags"
          alterable: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          placeholder: "/link/to/this/page"
          value: ""
      - name: "categories"
        field:
          element: "hidden"
          value: "projects"
    _posts/team:
      - name: "title"
        field:
          element: "text"
          label: "Name"
          value: "Full Name"
      - name: "role"
        field:
          element: "text"
          label: "Role"
          value: ""
          placeholder: "Job Title"
      - name: "excerpt"
        field:
          element: "text"
          label: "Two-line excerpt from Bio"
          value: ""
      - name: "email"
        field:
          element: "text"
          label: "Email Address"
          value: ""
          placeholder: "Enter email"
      - name: "twitter"
        field:
          element: "text"
          label: "Twitter Profile"
          value: ""
          placeholder: "Enter URL"
      - name: "image"
        field:
          element: "text"
          label: "Profile image"
          value: ""
          placeholder: "Enter a URL"
      - name: "background-image"
        field:
          element: "text"
          label: "Background image (shown on individual details page)"
          value: ""
          placeholder: "Enter a URL"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          placeholder: "/link/to/this/page"
          value: ""
      - name: "tags"
        field:
          element: "select"
          label: "Core Team / Board / Advisor"
          placeholder: "Select an option"
          options:
            - name: "Core Team"
              value: "core"
            - name: "Board"
              value: "board"
            - name: "Advisor"
              value: "advisor"
      - name: "categories"
        field:
          element: "hidden"
          value: "team"
