backend:
  name: git-gateway
  branch: master
  squash_merges: true

publish_mode: editorial_workflow
site_url: https://www.digital-democracy.org

media_folder: "assets"
public_folder: "/assets"

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "blog"
    label: "Blog posts"
    label_singular: "Blog post"
    folder: "_posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{year}}-{{month}}-{{day}} {{title}}"
    sortable_fields: ['date', 'commit_date', 'title']
    editor:
      preview: false
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Author
        field: author
    fields:
      - {label: "Categories", name: "categories", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      ## publish boolean is unnecessary now with the CMS, it has a built-in preview process
      - {label: "Published", name: "published", widget: "hidden", default: true}
      - {label: "Publish Date", name: "date", format: "YYYY-MM-DD", date_format: "LL", time_format: false, widget: "datetime"}
      - {label: "Excerpt", name: "excerpt", widget: "text", hint: "This excerpt is used for the blog posts on the front page and in list view. If this is blank the first paragraph of the post will be used"}
      - {label: "Author", name: "author", widget: "string", hint: "This should be the full name, matching the full name used in the team page metadata (if writer is on that page)"}
      - {label: "Featured Image", name: "image", widget: "image", required: true, hint: "Main header image for blog post"}
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["featured"]
        hint: "The most recent post with the 'featured' tag will appear at the top of the blog page"
      - label: "Slug for URL"
        name: "slug"
        widget: "string"
        hint: "Customize the URL for this page, e.g. if you put 'my-blog-post' here, the page URL will be /blob/my-blog-post"
        pattern: ['^[a-z0-9_-]*$', 'The slug must only contain lowercase a-Z, numbers, underscore _, or hyphen -']
      - label: "Post body"
        name: "body"
        widget: "markdown"
        editor_components: ['image']
  - name: "team"
    label: "Team members"
    label_singular: "Team member"
    folder: "_team_and_board"
    create: true
    summary: "{{title}} ({{fields.role}})"
    filter: {field: "tags", value: "core"}
    slug: "{{slug}}"
    editor:
      preview: false
    view_groups:
      - label: "Role"
        field: "role"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "core"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "team"}
      - {label: "Image", name: "image", widget: "image", required: true, hint: "A headshot, must be square (1:1)"}
      - label: "Slug for URL"
        name: "slug"
        widget: "string"
        hint: "Customize the URL for this page, e.g. if you put 'bob' here, the page URL will be /team/bob"
        pattern: ['^[a-z0-9_-]*$', 'The slug must only contain lowercase a-Z, numbers, underscore _, or hyphen -']
      - label: "Twitter"
        name: "twitter"
        widget: "string"
        hint: "URL of a twitter profile e.g. https://twitter.com/emjacobi"
        pattern: ['^https:\/\/twitter\.com\/.*', 'Must be a URL starting with https://twitter.com/']
      - {label: "Bio", name: "body", widget: "markdown"}
  - name: "board"
    label: "Board members"
    label_singular: "Board member"
    folder: "_team_and_board"
    create: true
    summary: "{{title}}"
    filter: {field: "tags", value: "board"}
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string", default: "Board"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "board"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "team"}
      - {label: "Image", name: "image", widget: "image", required: true, hint: "A headshot, must be square (1:1)"}
      - label: "Slug for URL"
        name: "slug"
        widget: "string"
        hint: "Customize the URL for this page, e.g. if you put 'bob' here, the page URL will be /team/bob"
        pattern: ['^[a-z0-9_-]*$', 'The slug must only contain lowercase a-Z, numbers, underscore _, or hyphen -']
      - label: "Twitter"
        name: "twitter"
        widget: "string"
        hint: "URL of a twitter profile e.g. https://twitter.com/emjacobi"
        pattern: ['^https:\/\/twitter\.com\/.*', 'Must be a URL starting with https://twitter.com/']
      - {label: "Bio", name: "body", widget: "markdown"}
  - name: "jobs"
    label: "Job Postings"
    label_singular: "Job Posting"
    folder: "_jobs"
    create: true
    slug: "{{slug}}"
    filter: {field: "published", value: true}
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "job"}
      - {label: "Job Title", name: "title", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - label: "Slug for URL"
        name: "slug"
        widget: "string"
        hint: "Customize the URL for this page, e.g. if you put 'my-blog-post' here, the page URL will be /blob/my-blog-post"
        pattern: ['^[a-z0-9_-]*$', 'The slug must only contain lowercase a-Z, numbers, underscore _, or hyphen -']
      - label: "Post body"
        name: "body"
        widget: "markdown"
        editor_components: []
